import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import FontLoader from '../src/components/FontLoader';
import ClientProviders from './ClientProviders';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        {/* Client-only font loader to avoid SSR/client class mismatches */}
        <FontLoader
          geistSans={geistSans.variable}
          geistMono={geistMono.variable}
        />
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
